config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: 'visitors#index'
  resources :executions, only: [:index]
end

app/models/execution.rb
class Execution < ActiveRecord::Base
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base

  has_many :executions, dependent: :destroy

  after_save :refresh_queue_job
  before_save :join_execution_days
  after_find :split_execution_days
  before_destroy :dequeue_job

  validates_presence_of :name, :executable_path, :command, :start_at, :end_at, :execution_days, :execution_server, :run_at_time

  def enqueue_job
    if next_run_at_time && next_run_at_time <= self.end_at.end_of_day
      Resque.enqueue_at_with_queue(self.execution_server, next_run_at_time, JobProcessor, self.id)
    end
  end

  def execute!
    current_execution = self.executions.create(start_at: DateTime.now)
    `cd #{self.executable_path} && #{self.command}`
    puts 'here'
    current_execution.end_at = DateTime.now
    current_execution.status = $?.exitstatus == 0 ? 'Success' : 'Failure'
    current_execution.save
    enqueue_job
  end

  def join_execution_days
    self.execution_days = self.execution_days.reject{|d| d.blank?}.join('|') if self.execution_days.is_a?(Array)
  end

  def split_execution_days
    self.execution_days = self.execution_days.split('|')
  end

  def next_run_at_time
    self.split_execution_days if self.execution_days.is_a?(String)
    ScheduleParser.next_schedule_for(self.execution_days, self.run_at_time)
  end

  def refresh_queue_job
    dequeue_job
    enqueue_job
  end

  def dequeue_job
    Resque.remove_delayed_selection {|args| args[0] == self.id }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController

  def index
    @executions = Execution.all
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :run_at_time, :executable_path, :command, :start_at, :end_at, :execution_server, execution_days: [])
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/executions_helper.rb
module ExecutionsHelper

  def calculate_execution_time(execution)
    begin
      time = (execution.end_at - execution.start_at).round
      "#{time} seconds"
    rescue
      "NA"
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def available_server_options
    {'Test Server A' => 'test_server_a', 'Test Server B' => 'test_server_b', 'Test Server C' => 'test_server_c'}
  end

  def execution_days_options
    ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  end

end

app/views/executions/index.html.erb
<%- model_class = Execution -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table summary="task table" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= 'Task Executed' %></th>
            <th><%= model_class.human_attribute_name(:start_at) %></th>
            <th><%= model_class.human_attribute_name(:end_at) %></th>
            <th><%= 'Execution Time' %></th>
            <th><%= 'Status' %></th>
          </tr>
        </thead>
        <tbody>
          <% @executions.each do |execution| %>
            <tr>
              <td><%= execution.task.name %></td>
              <td><%= execution.start_at %></td>
              <td><%= execution.end_at %></td>
              <td><%= calculate_execution_time(execution) %></td>
              <td><%= execution.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--end of .table-responsive-->
  </div>
</div>

<%= link_to t('.new', :default => 'New Task'), new_task_path, :class => 'btn btn-primary' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Executions', executions_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scheduler Client" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scheduler Client" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@task[:name]) %>
  <%= f.input :executable_path %>
  <%= error_span(@task[:executable_path]) %>
  <%= f.input :command %>
  <%= error_span(@task[:command]) %>
  <%= f.input :start_at, as: :string %>
  <%= error_span(@task[:start_at]) %>
  <%= f.input :run_at_time, as: :string, input_html: { class: 'bootstrap-timepicker'} %>
  <%= error_span(@task[:run_at_time]) %>
  <%= f.input :end_at, as: :string %>
  <%= error_span(@task[:end_at]) %>
  <%= f.input :execution_days, as: :select, collection: execution_days_options, input_html: {name: 'task[execution_days][]', multiple: true} %>
  <%= error_span(@task[:execution_days]) %>
  <%= f.input :execution_server, as: :select, collection: available_server_options %>
  <%= error_span(@task[:execution_server]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn btn-default' %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $( "input#task_start_at, input#task_end_at" ).datepicker({
      format: 'yyyy-mm-dd',
      startDate: '+0d',
      orientation: "top left"
    });
    $('#task_run_at_time').timepicker({
      minuteStep: 1,
      showMeridian: false,
      icons: {
        up: 'glyphicon glyphicon-chevron-up',
        down: 'glyphicon glyphicon-chevron-down'
      }
    });
  });
</script>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="table-responsive">
      <table summary="task table" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:id) %></th>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:executable_path) %></th>
            <th><%= model_class.human_attribute_name(:command) %></th>
            <th><%= model_class.human_attribute_name(:start_at) %></th>
            <th><%= model_class.human_attribute_name(:end_at) %></th>
            <th><%= model_class.human_attribute_name(:execution_days) %></th>
            <th><%= model_class.human_attribute_name(:execution_server) %></th>
            <th><%= model_class.human_attribute_name(:created_at) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
        </thead>
        <tbody>
          <% @tasks.each do |task| %>
            <tr>
              <td><%= link_to task.id, task_path(task) %></td>
              <td><%= task.name %></td>
              <td><%= task.executable_path %></td>
              <td><%= task.command %></td>
              <td><%= task.start_at %></td>
              <td><%= task.end_at %></td>
              <td><%= task.execution_days %></td>
              <td><%= task.execution_server %></td>
              <td><%=l task.created_at %></td>
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_task_path(task), :class => 'btn btn-default btn-xs' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            task_path(task),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--end of .table-responsive-->
  </div>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:executable_path) %>:</strong></dt>
  <dd><%= @task.executable_path %></dd>
  <dt><strong><%= model_class.human_attribute_name(:command) %>:</strong></dt>
  <dd><%= @task.command %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @task.start_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @task.end_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:execution_days) %>:</strong></dt>
  <dd><%= @task.execution_days %></dd>
  <dt><strong><%= model_class.human_attribute_name(:execution_server) %>:</strong></dt>
  <dd><%= @task.execution_server %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">
    <h2>Scheduler Client</h2>
    <h4>Pre-requisites:</h4>
    <ul>
      <li>Ruby v 2.2.3</li>
      <li>Rails v 4.1.14</li>
      <li>Mysql</li>
      <li>Redis</li>
    </ul>

    <ol>
      <li>
        <h4>Steps to prepare the source code:</h4>
        <ul>
          <li>Navigate to the project directory from terminal.</li>
          <li>Issue command - 'bundle install'. This will install all rubygems in your machine.</li>
        </ul>
      </li>
      <li>
        <h4>Steps to create and initialize the database:</h4>
        <ul>
          <li>Copy the settings given in 'config/database.example.yml'</li>
          <li>Write those into a new file called 'database.yml' in the /config dir.</li>
          <li>Write suitable username and password for the Mysql DB of your machine in database.yml file.</li>
          <li>
            Run the commands -
            <ol>
              <li>rake db:create</li>
              <li>rake db:migrate</li>
              <li>rake db:seed</li>
            </ol>
          </li>
        </ul>
      </li>
      <li>
        <h4>Assumptions made:</h4>
        <p>Setting up agents</p>
        <p>We have used resque (which used redis in background) as the agent which will execute scheduled tasks. Make sure you have redis installed and running on port 6379. Assumption is made that we would be having 3 test server options (A, B, C) for executing tasks. These would be running locally in separate terminals.</p>
        <p>
          To get agents working, please run following tasks in separate terminals from within the project directory:
        </p>
        <ol>
          <li>rake resque:scheduler</li>
          <li>rake resque:work QUEUE='test_server_a'</li>
          <li>rake resque:work QUEUE='test_server_b'</li>
          <li>rake resque:work QUEUE='test_server_c'</li>
        </ol>
        <p>Now, while creating a new scheduled task, you need to select execution server from front-end. Based on the server you select, appropriate queue would be handling the execution of the task.</p>
      </li>
      <li>
        <h4>Working:</h4>
        <ul>
          <li>To get started with the application, click on the 'Executions' tab.</li>
          <li>You will get a page, where list of exceutions will be shown and a button for 'New task'. Click on the button.</li>
          <li>Create a task by filling up all details. All the fields are mandatory.</li>
          <li>Task created will have start_at and end_at fields along with set of execution days, which will determine, when the task will be executed.</li>
          <li>Once the task gets executed, you will get to see the time taken and other stats in the table.</li>
        </ul>
      </li>

    </ol>
  </div>
    <!-- /.row -->

  <hr>

    <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Scheduler Client 2016</p>
      </div>
        <!-- /.col-lg-12 -->
    </div>
      <!-- /.row -->
  </footer>

</div>
<!-- /.container -->